# Generated by Django 5.2.4 on 2025-11-02 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GunlukMesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('mesaj', models.TextField()),
                ('mesaj_tipi', models.CharField(choices=[('GUNAYDIN', 'Günaydın Mesajı'), ('MOTIVASYON', 'Motivasyon Mesajı'), ('DINI', 'Dini İçerik'), ('EGITIM', 'Eğitim Tavsiyesi'), ('KISISEL', 'Kişisel Gelişim'), ('DUYGU', 'Duygusal Destek'), ('BASARI', 'Başarı Hikayeleri'), ('DIGER', 'Diğer')], default='MOTIVASYON', max_length=10)),
                ('okundu', models.BooleanField(default=False)),
                ('begeni', models.BooleanField(default=False, verbose_name='Beğendi mi?')),
                ('not_puani', models.PositiveSmallIntegerField(blank=True, help_text='1-10 arası puan', null=True)),
                ('ek_notlar', models.TextField(blank=True, verbose_name="Şeyma'nın Notları")),
                ('ai_generated', models.BooleanField(default=True)),
                ('ai_prompt', models.TextField(blank=True, verbose_name='Kullanılan AI Prompt')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Günlük Mesaj',
                'verbose_name_plural': 'Günlük Mesajlar',
                'ordering': ['-tarih'],
            },
        ),
    ]
