# Generated by Django 5.2.4 on 2025-11-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0002_gunlukmesaj'),
    ]

    operations = [
        migrations.CreateModel(
            name='BildirimAbonelik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh_key', models.TextField()),
                ('auth_key', models.TextField()),
                ('aktif', models.BooleanField(default=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bildirim Aboneliği',
                'verbose_name_plural': 'Bildirim Abonelikleri',
            },
        ),
        migrations.CreateModel(
            name='BildirimGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('GUNLUK_MESAJ', 'Günlük Kişisel Mesaj'), ('HAFTALIK_RAPOR', 'Haftalık Öğrenci Raporu'), ('SISTEM', 'Sistem Bildirimi'), ('HOSGELDIN', 'Hoş Geldin Mesajı')], max_length=20)),
                ('baslik', models.CharField(max_length=200)),
                ('icerik', models.TextField()),
                ('gonderilme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('basarili_gonderim', models.PositiveIntegerField(default=0)),
                ('basarisiz_gonderim', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bildirim Geçmişi',
                'verbose_name_plural': 'Bildirim Geçmişleri',
                'ordering': ['-gonderilme_tarihi'],
            },
        ),
    ]
