# Generated by Django 5.2.4 on 2025-11-04 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0003_bildirimabonelik_bildirimgecmisi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KonusmaOturumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(blank=True, max_length=200)),
                ('baslama_zamani', models.DateTimeField(auto_now_add=True)),
                ('son_mesaj_zamani', models.DateTimeField(auto_now=True)),
                ('aktif', models.BooleanField(default=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konusma_oturumlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Konuşma Oturumu',
                'verbose_name_plural': 'Konuşma Oturumları',
                'ordering': ['-son_mesaj_zamani'],
            },
        ),
        migrations.CreateModel(
            name='KonusmaMesaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('USER', 'Kullanıcı'), ('AI', 'Şeyma (AI)')], max_length=4)),
                ('icerik', models.TextField()),
                ('zaman', models.DateTimeField(auto_now_add=True)),
                ('oturum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='mainproject.konusmaoturumu')),
            ],
            options={
                'verbose_name': 'Konuşma Mesajı',
                'verbose_name_plural': 'Konuşma Mesajları',
                'ordering': ['zaman'],
            },
        ),
    ]
