# Generated by Django 5.2.4 on 2025-11-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0004_konusmaoturumu_konusmamesaji'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkilliBildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('GUNLUK', 'Günlük Motivasyon'), ('YAZI', 'Yazı Analizi'), ('ALINTI', 'Alıntı Yorumu'), ('OGRENCI', 'Öğrenci Raporu'), ('EZBER', 'Ezber İstatistikleri')], max_length=10)),
                ('baslik', models.CharField(max_length=200)),
                ('mesaj', models.TextField()),
                ('olusturma_zamani', models.DateTimeField(auto_now_add=True)),
                ('okundu', models.BooleanField(default=False)),
                ('ilgili_yazi_id', models.IntegerField(blank=True, null=True)),
                ('ilgili_alinti_id', models.IntegerField(blank=True, null=True)),
                ('ilgili_ogrenci_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Akıllı Bildirim',
                'verbose_name_plural': 'Akıllı Bildirimler',
                'ordering': ['-olusturma_zamani'],
            },
        ),
    ]
