# Generated by Django 5.2.4 on 2025-11-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0005_akillibildirim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(help_text='Fotoğraf başlığı', max_length=200)),
                ('aciklama', models.TextField(blank=True, help_text='Fotoğraf açıklaması')),
                ('dosya', models.ImageField(help_text='Fotoğraf dosyası', upload_to='galeri/%Y/%m/')),
                ('kategori', models.CharField(choices=[('YAZI', 'Yazı Fotoğrafı'), ('MANUEL', 'Manuel Yükleme'), ('OGRENCI', 'Öğrenci Profil'), ('GENEL', 'Genel')], default='GENEL', max_length=10)),
                ('yukleme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('dosya_boyutu', models.PositiveIntegerField(blank=True, help_text='KB cinsinden boyut', null=True)),
                ('genislik', models.PositiveIntegerField(blank=True, null=True)),
                ('yukseklik', models.PositiveIntegerField(blank=True, null=True)),
                ('ilgili_yazi_id', models.PositiveIntegerField(blank=True, help_text='Hangi yazıya ait', null=True)),
            ],
            options={
                'verbose_name': 'Galeri Fotoğrafı',
                'verbose_name_plural': 'Galeri Fotoğrafları',
                'ordering': ['-yukleme_tarihi'],
            },
        ),
    ]
