# Generated by Django 5.2.4 on 2025-11-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='date',
            field=models.DateField(),
        ),
    ]
