# Generated by Django 5.2.4 on 2025-11-04 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_yazi_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
